### ISSUE TITLE
Собрать метрики по книге (составить перечень метрик )

### ISSUE THREAD

**Issue by olovekb** [igorplyukhin/E-readerWithAI#15]
**Исполнитель:** Архипов Роман

**Описание:** Изучить ПО. Составить перечень метрик для сбора

**Comment by qSHEMq** [comment]
[Метрики.pdf](https://github.com/user-attachments/files/17242689/default.pdf)

Собрал возможные метрики и распределил по категориям, не стал включать те, которые собирают данные для бизнес-аналитики
