### ISSUE TITLE
Встроить загрузку файлов PDF, TXT, FB2 в мобильное приложение

### ISSUE THREAD

**Issue by olovekb** [igorplyukhin/E-readerWithAI#20]

**Comment by olovekb** [comment]
PDF, TXT, FB2

**Comment by olovekb** [comment]
Необходимо встроить загрузку файлов указанного формата. Протестировать работу могу я

**Comment by NataliaMaltseva** [comment]
Добавить возможность переименовать файл или взять часть для заголовка и аннотации
