### ISSUE TITLE
Реализовать отображение книги в мобильном приложении

### ISSUE THREAD

**Issue by igorplyukhin** [igorplyukhin/E-readerWithAI#28]

**Comment by Shoolife** [comment]
![Image](https://github.com/user-attachments/assets/78119400-b513-4fc9-9e35-db1c0a0c1108)
![Image](https://github.com/user-attachments/assets/d9dfa4f8-094a-4371-ab21-fa8b948e32c1)
![Image](https://github.com/user-attachments/assets/28de9432-b7d8-415d-9be0-0bd68a3f81cb)
Окно список книг, Окно аннотации, Окно чтения
