### ISSUE TITLE
Исследование альтернативных LLM (модели) для работы с текстом

### ISSUE THREAD

**Issue by igorplyukhin** [igorplyukhin/E-readerWithAI#3]
Ринат
Найти и описать готовые методы позволяющие
1 сжатию текста по содержанию
2 составлению тестов на основе текста

**Comment by NataliaMaltseva** [comment]
Протестировали ГигаЧат, GPT4_omin, CLAUDE

<html>
<body>
<google-sheets-html-origin><style type="text/css"></style>
Гига Чат справляется |   | формирует вопросы
-- | -- | --
  |   | список вариантов ответов
  |   | правильный ответ внизу
  |   | делает открытые вопросы
Тест на |   | технической и художственной


</body>
</html>

**Comment by igorplyukhin** [comment]
Есть ли более удобные модели для нашей задачи, их преимущества?

**Comment by olovekb** [comment]
Определились что нужен Гигачат, используем его, потому что это продукт Сбера + так было установлено ТЗ, альтернативные варианты не сильно лучше
