### ISSUE TITLE
Подготовить презентацию к 5.11

### ISSUE THREAD

**Issue by igorplyukhin** [igorplyukhin/E-readerWithAI#31]
План презентации
1 ТЗ проекта
2 В проекте уже были некоторые данные, которые формировали ТЗ. 
3 было принято решение делать мобилку
4 начать сразу с демо мобилки на эмуляторе
5 показать работу бэка
6 численные результаты
7 кинуть удочку для ресурсов(сервак, подписка)
8 дальнейшие планы

**Comment by olovekb** [comment]
https://urfume-my.sharepoint.com/:p:/g/personal/oleg_ankudinov_urfu_me/EQKIc2RJBulBklYoYop-pQYBVc3390jynlHrlIOJUsSY0Q?e=AsVK7N
